default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: storage/development.sqlite3  # This will store your SQLite database file in the storage directory

test:
  <<: *default
  adapter: sqlite3
  database: storage/test.sqlite3  # This will store your SQLite test database in the storage directory

production:
  <<: *default
  adapter: postgresql
  database: <%= ENV['DATABASE_URL'] %>  # This fetches the PostgreSQL database URL from environment variables
  username: <%= ENV['DATABASE_USER'] %>  # Use environment variable for security
  password: <%= ENV['DATABASE_PASSWORD'] %>  # Use environment variable for security
  host: <%= ENV['DATABASE_HOST'] %>  # This can be localhost or your production host
  port: 5432  # Default PostgreSQL port
